# NumPy Practice Notebook

In [5]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.0.2


In [6]:
#Creating 1D arrays
arr_1d = np.array([10, 20, 30, 40, 50])

print("1D Array:", arr_1d)

#Creating 2D arrays
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("2D Array:")
print(arr_2d)

#Creating 2D arrays
arr_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("3D Array:")
print(arr_3d)

1D Array: [10 20 30 40 50]
2D Array:
[[1 2 3]
 [4 5 6]]
3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


1.ndim → number of dimensions
2.shape → size of each dimension
3.dtype → data type of elements

In [7]:
#Dimensions and data types
print("Dimensions:", arr_2d.ndim)
print("Shape:", arr_2d.shape)
print("Data type:", arr_2d.dtype)

Dimensions: 2
Shape: (2, 3)
Data type: int64


In [8]:
#Indexing
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[-1])

10
30
50


In [9]:
#Slicing
print(arr[1:4])
print(arr[:3])
print(arr[2:])

[20 30 40]
[10 20 30]
[30 40 50]


In [10]:
#Reshaping
arr = np.arange(1, 13)

reshaped = arr.reshape(3, 4)

print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
#zeros()
zeros_array = np.zeros((3, 4))

print(zeros_array)

#ones()
ones_array = np.ones((2, 3))

print(ones_array)

#arange()
arr = np.arange(1, 11)

print(arr)

#linspace()
arr = np.linspace(0, 10, 5)

print(arr)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 0.   2.5  5.   7.5 10. ]


Mathematical operations

In [12]:
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Square:", a ** 2)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]
Square: [100 400 900]


Vectorized operations

In [13]:
arr = np.array([1, 2, 3, 4, 5])

result = arr * 10

print(result)

[10 20 30 40 50]


Boolean masking

In [14]:
arr = np.array([10, 25, 30, 15, 40, 5])

mask = arr > 20

print(mask)
print(arr[mask])

[False  True  True False  True False]
[25 30 40]


Broadcasting

In [15]:
arr = np.array([10, 20, 30])

result = arr + 5

print(result)

#2D broadcasting
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

result = arr + 10

print(result)

[15 25 35]
[[11 12 13]
 [14 15 16]]


Aggregate functions

In [16]:
arr = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Median:", np.median(arr))

Sum: 150
Mean: 30.0
Minimum: 10
Maximum: 50
Median: 30.0
